/**
 * Usage: Build a min-cut tree. Query: DFS/BFS on tree find min weight on path (OR) LCA + binary jumping with min.
 * 
 * Output: edges list with form {u, v, w}; min cut(u, v) = min weight of an edge of the path u-v on tree generated by gomoryHu.
 * 
 * Time: $O(V^2 \times E)$ for initializing DinicFlow.
*/

vector<array<ll, 3>> gomoryHu(int n, const vector<array<ll, 3>>& edges) {
    vector<int> par(n, 0); vector<ll> wt(n, 0);
    for (int i = 1; i < n; i++) {
        Dinic D(n);
        for (auto [u, v, c] : edges) D.addEdge(u, v, c, c);
        wt[i] = D.maxflow(i, par[i]);
        vector<char> side = D.minCutSide(i);
        for (int j = i + 1; j < n; j++) if (side[j] && par[j] == par[i]) par[j] = i;
    }
    vector<array<ll, 3>> tree;
    for (int i = 1; i < n; i++) tree.push_back({i, par[i], wt[i]});
    return tree;
}